In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# [Numpy](https://numpy.org/doc/stable/index.html#)

## numpy常见的属性

In [2]:
array = np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6]
])
#输出矩阵
print(array)

#输出维度
print("number of dimension:", array.ndim)

#输出行列
print("shape:", array.shape)

#输出元素个数
print("size:", array.size)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
number of dimension: 2
shape: (3, 4)
size: 12


## narray的创建
### 通过np的array()方法,赋值list或者tuple

In [7]:
#基础创建
a = np.array([123, 23, 4], dtype=int)  # 通过dtype的数据类型 包括int int32 float64 float32
print(a)
print(a.dtype)

list1 = ['testArray', 23, 4]
a = np.array(list1)
print(a)
print(a.dtype)

tuple1 =('testArray1', 231, 41)
a = np.array(tuple1)
print(a)
print(a.dtype)

[123  23   4]
int64
['testArray' '23' '4']
<U9
['testArray1' '231' '41']
<U10


### 对象元素类型
![元素类型](./res/elementType.png)

### 创建0矩阵

In [8]:
#特殊创建
#创建全部为0的矩阵
zeroArray = np.zeros((3, 4))  #创建了一个三行四列的零矩阵
zeroArray

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 数组复制

In [32]:
array_new = zeroArray[:]
print(array_new.base)
# 数组的复制区别于list的切片操作,其内存空间相同,而list不同

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 范围创建一维数组与reshape

In [33]:
#创建范围（手动指定步长）
rangeArray1 = np.arange(1, 10, 3)  # 大于等于1小于10，左开右闭 步进值=3
print(rangeArray1)  # 默认为一行

rangeArray2 = np.arange(1, 10).reshape((3, 3))  # reshape的大小必须与前面的范围相同
print(rangeArray2)

rangeArray3 = np.arange(12).reshape((3, 4))  # 默认从0开始
print(rangeArray3)

[1 4 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
#创建范围（自动分配步长）
lineArray = np.linspace(1, 19, 10).reshape((2, 5))  #x大于等于1小于等于19，平均选择10个值
print(lineArray)

[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]]


### 随机数矩阵

In [25]:
array4 = np.random.randint(1,4,5).reshape((1,5))
array4

array([[1, 3, 3, 2, 1]])

### 单位矩阵

In [29]:
array = np.eye(4)
array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## numpy基础运算

In [10]:
# 创建两个一行四列的一维数组
arrayA = np.array([10, 20, 30, 40], dtype=int)
# arrayB=np.arange(0,4)
arrayB = np.arange(1, 5)
print(arrayA, arrayB)  # [10 20 30 40] [1 2 3 4]

[10 20 30 40] [1 2 3 4]


### 加减乘除

In [11]:
# 元素按顺序逐个一一相加减乘除
print(arrayA - arrayB)
print(arrayA + arrayB)
c = arrayA * arrayB
print(c.dtype, c)
try:
    c = arrayA / arrayB  #使用除法后 数据类型变为float64
    print(c.dtype, c)
except ZeroDivisionError:
    print("错误 除以0了")

[ 9 18 27 36]
[11 22 33 44]
int64 [ 10  40  90 160]
float64 [10. 10. 10. 10.]


In [12]:
# 次数运算
print(arrayA ** 2)
# 三角函数运算
print(np.sin(arrayA))

[ 100  400  900 1600]
[-0.54402111  0.91294525 -0.98803162  0.74511316]


### 元素大小判断

In [22]:
# 直接判断元素的大小
print(arrayB==3)
print(arrayB<3)

[False False  True False]
[ True  True False False]


### 矩阵相乘

In [28]:
# 矩阵的运算
rectA=np.array([
    [1,1],
    [0,1]])
rectB=np.arange(4).reshape((2,2))
print(rectA,'\n',rectB)
rectA.dot(rectB)
# 矩阵乘法 注意：不要使用rectA*rectB 这样计算是按照坐标挨个相乘的结果

[[1 1]
 [0 1]] 
 [[0 1]
 [2 3]]


array([[2, 4],
       [2, 3]])

### 矩阵的单目运算

In [30]:
rect_random=np.arange(1,5).reshape((2,2))#在0到1之间随机产生数字组成一个矩阵
print(rect_random,
      rect_random.sum(axis=0),# axis=0时，针对行数进行求和，axis=1时，针对列数分别求和，不添加时针对所有元素进行求和
      rect_random.min(axis=1),
      rect_random.max(),
      rect_random.mean(),
      np.median(rect_random))#中位数

[[1 2]
 [3 4]] [4 6] [1 3] 4 2.5 2.5


In [34]:
rect_a=np.arange(2,14).reshape((3,4))
print(rect_a)
print(rect_a.argmin())# 求数列中最小值的索引
print(rect_a.cumsum())# 累加到一位数列

rect_b=np.arange(14,2,-1).reshape((3,4))
print(rect_b)
print(np.sort(rect_b,axis=0))# 重拍序列

print(rect_a.T)# 矩阵的转置 

print(rect_a.clip(5,9)) # 设置阈值 小于5都设置成5 大于9都设置成9


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[ 6  5  4  3]
 [10  9  8  7]
 [14 13 12 11]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


## numpy的索引运算

In [ ]:
array_indexa=np.arange(3,15).reshape((2,3,2))
print(array_indexa,'\n')
# print(array_indexa[1],'\n')
# print(array_indexa[1][2],'\n')# 与array_indexa[1,2]相同
# print(array_indexa[:,1],'\n')


# 输出每一行
for row in array_indexa:
    print(row,'\n')
    
# 通过转置矩阵输出每一列
for col in array_indexa.T:
    print(col,'\n')
    
# 输出每个元素  
for item in array_indexa.flat:# !!!数组（一维化之后）元素的迭代器
    print(item,'\n')

### 花式索引
Fancy index是指利用整数数组进行索引,这里的数组可以是ndarray,也可是其他可迭代对象

In [37]:
array12 = np.array([[30, 20, 10],
                  [40, 60, 50],
                  [10, 90, 80]])

array12[[1,2],1]

array([60, 90])

## array的合并与分割

In [106]:
# 合并
array_a=np.array([1,1,1])
array_b=np.array([2,3,4])
print(array_a,array_b)

print(np.vstack((array_a,array_b,array_a))) #将A和B在垂直方向上合并。 vertical
print(np.hstack((array_a,array_b))) #将A和B在水平方向上合并。 horizontal

print(np.vstack(array_a)) #转为竖向

[1 1 1] [2 3 4]
[[1 1 1]
 [2 3 4]
 [1 1 1]]
[1 1 1 2 3 4]
[[1]
 [1]
 [1]]


In [114]:
# 分割
array_a=np.arange(24).reshape((6,4))
print(array_a,'\n')

print(np.split(array_a,3,axis=0)) #按照行分割成三个数组
print(np.split(array_a,2,axis=1)) #按照列分割成两个数组

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])]


In [40]:
guido_img = plt.imread('./res/guido.jpg')